FLICKRAW_API_KEY = ENV["FLICKRAW_API_KEY"]
FLICKRAW_SHARED_SECRET = ENV["FLICKRAW_SHARED_SECRET"]
WORDNIK_API_KEY = ENV["WORDNIK_API_KEY"]
YOUTUBE_API_KEY = ENV["YOUTUBE_API_KEY"]
WOLFRAM_ALPHA_API_KEY = ENV["WOLFRAM_ALPHA_API_KEY"]
BIG_HUGE_LABS = ENV["BIG_HUGE_LABS"]
VERY_RELATED_API_KEY = ENV["VERY_RELATED_API_KEY"]
TWINWORD_API_KEY = ENV["TWINWORD_API_KEY"]

FlickRaw.api_key = FLICKRAW_API_KEY
FlickRaw.shared_secret = FLICKRAW_SHARED_SECRET